[metadata]
author = "Lay3r Labs Team"
description = "WAVS WASI Operator"
license = "MIT"
homepage = "https://www.wavs.xyz/"
repository = "https://github.com/Lay3rLabs/wavs-wasi"

[overrides]
"wavs:types" = { path = "../types/wit" }
"wasi:tls" = { path = "../wasi-tls/wit" }
